# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes@4.15.1"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
